# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sergio
title2: Pino
email: spino327@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
url: http://spino327.github.io

# twitter_username: jekyllrb
#github_username:  spino327
#linkedin_username: sergiopino

# Author settings
author:
  name     : "Sergio Pino"
  job      : "Software Engineer"
  bio      : ""
  thumb    : 
  email    : spino327@gmail.com
  url      : http://spino327.github.io/
  github   : spino327
  twitter  : Sergio_Pino_G
  linkedin : sergiopino
  google:
    plus: #username
    analytics: UA-30337201-2
    verify:
    ad-client:
    ad-slot:

# Build settings
markdown: kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

#theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate

# Paginate
paginate: 5

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
